<?php

namespace AppBundle\Repository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllActiveSortedByDate()
    {
        return $this->createQueryBuilder('article')
            ->where('article.isDeleted = false')
            ->andWhere('article.isApproved = true')
            ->orderBy('article.id', 'DESC')
            ->getQuery();
    }
}
