<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Article;
use AppBundle\Entity\Comment;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param Article $article
     * @return \Doctrine\ORM\Query
     */
    public function findAllByArticle(Article $article)
    {
        return $this->createQueryBuilder('comment')
            ->where('comment.article = ' . $article->getId())
            ->andWhere('comment.isDeleted = false')
            ->orderBy('comment.id', 'DESC')
            ->getQuery();
    }
}
